# Form implementation generated from reading ui file 'manage_bookings.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(907, 639)
        palette = Form.palette()
        palette.setColor(QtGui.QPalette.ColorRole.Window, QtGui.QColor(169, 181, 223))
        Form.setAutoFillBackground(True)
        Form.setPalette(palette)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(-1, -1, -1, 25)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_5 = QtWidgets.QLabel(parent=Form)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 70))
        font = QtGui.QFont()
        font.setPointSize(40)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background-color: rgb(255, 242, 242);\n"
"color: rgb(45, 51, 107);\n"
"border-radius: 10px;")
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.tableView = QtWidgets.QTableView(parent=Form)
        self.tableView.setMinimumSize(QtCore.QSize(0, 50))
        self.tableView.setMaximumSize(QtCore.QSize(700, 300))
        self.tableView.setStyleSheet("background-color: rgb(255, 242, 242);\n"
"color: rgb(45, 51, 107);\n"
"border-radius: 10px;")
        self.tableView.setObjectName("tableView")
        self.verticalLayout.addWidget(self.tableView)
        self.refresh_table_btn = QtWidgets.QPushButton(parent=Form)
        self.refresh_table_btn.setMinimumSize(QtCore.QSize(0, 30))
        self.refresh_table_btn.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.refresh_table_btn.setFont(font)
        self.refresh_table_btn.setStyleSheet("QPushButton{\n"
"    background-color: rgb(45, 51, 107);\n"
"    color: rgb(255, 242, 242);\n"
"    border-radius: 10px;\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color:     rgb(255, 242, 242);\n"
"    color: rgb(45, 51, 107);\n"
"}\n"
"")
        self.refresh_table_btn.setObjectName("refresh_table_btn")
        self.verticalLayout.addWidget(self.refresh_table_btn)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(-1, -1, -1, 20)
        self.gridLayout.setHorizontalSpacing(20)
        self.gridLayout.setVerticalSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.update_booking_btn = QtWidgets.QPushButton(parent=Form)
        self.update_booking_btn.setMinimumSize(QtCore.QSize(0, 30))
        self.update_booking_btn.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.update_booking_btn.setFont(font)
        self.update_booking_btn.setStyleSheet("QPushButton{\n"
"    background-color: rgb(45, 51, 107);\n"
"    color: rgb(255, 242, 242);\n"
"    border-radius: 10px;\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color:     rgb(255, 242, 242);\n"
"    color: rgb(45, 51, 107);\n"
"}\n"
"")
        self.update_booking_btn.setObjectName("update_booking_btn")
        self.gridLayout.addWidget(self.update_booking_btn, 2, 0, 1, 3)
        self.room_id_change = QtWidgets.QLineEdit(parent=Form)
        self.room_id_change.setMinimumSize(QtCore.QSize(0, 30))
        self.room_id_change.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.room_id_change.setFont(font)
        self.room_id_change.setStyleSheet("background-color: rgb(255, 242, 242);\n"
"color: rgb(45, 51, 107);\n"
"border-radius: 10px;")
        self.room_id_change.setObjectName("room_id_change")
        self.gridLayout.addWidget(self.room_id_change, 1, 1, 1, 2)
        self.label_3 = QtWidgets.QLabel(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Ignored, QtWidgets.QSizePolicy.Policy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: rgb(120, 134, 199);\n"
"border-radius: 10px;\n"
"color: rgb(255, 242, 242);")
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 3, 1, 1)
        self.check_out_change = QtWidgets.QLineEdit(parent=Form)
        self.check_out_change.setMinimumSize(QtCore.QSize(0, 30))
        self.check_out_change.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.check_out_change.setFont(font)
        self.check_out_change.setStyleSheet("background-color: rgb(255, 242, 242);\n"
"color: rgb(45, 51, 107);\n"
"border-radius: 10px;")
        self.check_out_change.setObjectName("check_out_change")
        self.gridLayout.addWidget(self.check_out_change, 1, 4, 1, 1)
        self.label_4 = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color: rgb(120, 134, 199);\n"
"border-radius: 10px;\n"
"color: rgb(255, 242, 242);")
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 3, 1, 1)
        self.check_in_change = QtWidgets.QLineEdit(parent=Form)
        self.check_in_change.setMinimumSize(QtCore.QSize(0, 30))
        self.check_in_change.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.check_in_change.setFont(font)
        self.check_in_change.setStyleSheet("background-color: rgb(255, 242, 242);\n"
"color: rgb(45, 51, 107);\n"
"border-radius: 10px;")
        self.check_in_change.setObjectName("check_in_change")
        self.gridLayout.addWidget(self.check_in_change, 0, 4, 1, 1)
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setMinimumSize(QtCore.QSize(0, 50))
        self.label.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(120, 134, 199);\n"
"border-radius: 10px;\n"
"color: rgb(255, 242, 242);")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setMinimumSize(QtCore.QSize(100, 50))
        self.label_2.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgb(120, 134, 199);\n"
"border-radius: 10px;\n"
"color: rgb(255, 242, 242);")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.booking_id_lbl = QtWidgets.QLabel(parent=Form)
        self.booking_id_lbl.setMinimumSize(QtCore.QSize(138, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.booking_id_lbl.setFont(font)
        self.booking_id_lbl.setStyleSheet("background-color: rgb(255, 242, 242);\n"
"color: rgb(45, 51, 107);\n"
"border-radius: 10px;")
        self.booking_id_lbl.setObjectName("booking_id_lbl")
        self.gridLayout.addWidget(self.booking_id_lbl, 0, 2, 1, 1)
        self.cancel_booking_btn = QtWidgets.QPushButton(parent=Form)
        self.cancel_booking_btn.setMinimumSize(QtCore.QSize(0, 30))
        self.cancel_booking_btn.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cancel_booking_btn.setFont(font)
        self.cancel_booking_btn.setStyleSheet("QPushButton{\n"
"    background-color: rgb(45, 51, 107);\n"
"    color: rgb(255, 242, 242);\n"
"    border-radius: 10px;\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color:     rgb(255, 242, 242);\n"
"    color: rgb(45, 51, 107);\n"
"}\n"
"")
        self.cancel_booking_btn.setObjectName("cancel_booking_btn")
        self.gridLayout.addWidget(self.cancel_booking_btn, 2, 3, 1, 2)
        self.verticalLayout.addLayout(self.gridLayout)
        self.back_to_main_btn = QtWidgets.QPushButton(parent=Form)
        self.back_to_main_btn.setMinimumSize(QtCore.QSize(0, 30))
        self.back_to_main_btn.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.back_to_main_btn.setFont(font)
        self.back_to_main_btn.setStyleSheet("QPushButton{\n"
"    background-color: rgb(45, 51, 107);\n"
"    color: rgb(255, 242, 242);\n"
"    border-radius: 10px;\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color:     rgb(255, 242, 242);\n"
"    color: rgb(45, 51, 107);\n"
"}\n"
"")
        self.back_to_main_btn.setObjectName("back_to_main_btn")
        self.verticalLayout.addWidget(self.back_to_main_btn)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_5.setText(_translate("Form", "Manage Bookings"))
        self.refresh_table_btn.setText(_translate("Form", "Refresh table"))
        self.update_booking_btn.setText(_translate("Form", "update the booking"))
        self.label_3.setText(_translate("Form", "check-in date"))
        self.label_4.setText(_translate("Form", "check-out date"))
        self.label.setText(_translate("Form", "id of booking"))
        self.label_2.setText(_translate("Form", "room id"))
        self.booking_id_lbl.setText(_translate("Form", "id"))
        self.cancel_booking_btn.setText(_translate("Form", "cancel the booking "))
        self.back_to_main_btn.setText(_translate("Form", "Back to main menu"))
