# Form implementation generated from reading ui file 'customer_man_page.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(920, 642)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Ignored, QtWidgets.QSizePolicy.Policy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(920, 642))
        Form.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        palette = Form.palette()
        palette.setColor(QtGui.QPalette.ColorRole.Window, QtGui.QColor(169, 181, 223))
        Form.setAutoFillBackground(True)
        Form.setPalette(palette)
        self.gridLayout_3 = QtWidgets.QGridLayout(Form)
        self.gridLayout_3.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetNoConstraint)
        self.gridLayout_3.setContentsMargins(30, -1, 5, -1)
        self.gridLayout_3.setSpacing(20)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetNoConstraint)
        self.gridLayout.setContentsMargins(10, -1, 100, -1)
        self.gridLayout.setHorizontalSpacing(60)
        self.gridLayout.setVerticalSpacing(20)
        self.gridLayout.setObjectName("gridLayout")
        self.customer_list = QtWidgets.QTableView(parent=Form)
        self.customer_list.setMinimumSize(QtCore.QSize(455, 0))
        self.customer_list.setMaximumSize(QtCore.QSize(16777215, 350))
        self.customer_list.setStyleSheet("background-color: rgb(255, 242, 242);\n"
"color: rgb(45, 51, 107);")
        self.customer_list.setObjectName("customer_list")
        self.gridLayout.addWidget(self.customer_list, 0, 0, 1, 2)
        self.refresh_button = QtWidgets.QPushButton(parent=Form)
        self.refresh_button.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.refresh_button.setFont(font)
        self.refresh_button.setStyleSheet("QPushButton {\n"
"    background-color: rgb(45, 51, 107);\n"
"    border-radius: 7px;\n"
"    color: rgb(255, 242, 242);\n"
"    \n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(255, 242, 242);\n"
"    border-radius: 7px;\n"
"    color: rgb(120, 134, 199);\n"
"}\n"
"")
        self.refresh_button.setObjectName("refresh_button")
        self.gridLayout.addWidget(self.refresh_button, 1, 0, 1, 1)
        self.delete_button = QtWidgets.QPushButton(parent=Form)
        self.delete_button.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.delete_button.setFont(font)
        self.delete_button.setStyleSheet("QPushButton {\n"
"    background-color: rgb(45, 51, 107);\n"
"    border-radius: 7px;\n"
"    color: rgb(255, 242, 242);\n"
"    \n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(255, 242, 242);\n"
"    border-radius: 7px;\n"
"    color: rgb(120, 134, 199);\n"
"}\n"
"")
        self.delete_button.setObjectName("delete_button")
        self.gridLayout.addWidget(self.delete_button, 1, 1, 1, 1)
        self.back_tomain_menu = QtWidgets.QPushButton(parent=Form)
        self.back_tomain_menu.setMinimumSize(QtCore.QSize(170, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.back_tomain_menu.setFont(font)
        self.back_tomain_menu.setStyleSheet("QPushButton {\n"
"    background-color: rgb(45, 51, 107);\n"
"    border-radius: 7px;\n"
"    color: rgb(255, 242, 242);\n"
"    \n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(255, 242, 242);\n"
"    border-radius: 7px;\n"
"    color: rgb(120, 134, 199);\n"
"}\n"
"")
        self.back_tomain_menu.setObjectName("back_tomain_menu")
        self.gridLayout.addWidget(self.back_tomain_menu, 2, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 1, 2, 1, 1)
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setMinimumSize(QtCore.QSize(450, 50))
        self.label.setMaximumSize(QtCore.QSize(16777215, 80))
        font = QtGui.QFont()
        font.setPointSize(45)
        self.label.setFont(font)
        self.label.setStyleSheet("border-radius: 15px;\n"
"background-color: rgb(255, 242, 242);\n"
"color: rgb(45, 51, 107);")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 3)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetNoConstraint)
        self.gridLayout_2.setContentsMargins(-1, -1, 50, 120)
        self.gridLayout_2.setHorizontalSpacing(20)
        self.gridLayout_2.setVerticalSpacing(10)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.phone_label = QtWidgets.QLabel(parent=Form)
        self.phone_label.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.phone_label.setFont(font)
        self.phone_label.setStyleSheet("color: rgb(255, 242, 242);\n"
"border-radius: 7px;\n"
"")
        self.phone_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.phone_label.setObjectName("phone_label")
        self.gridLayout_2.addWidget(self.phone_label, 3, 0, 1, 1)
        self.booking_date_lbl = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.booking_date_lbl.setFont(font)
        self.booking_date_lbl.setStyleSheet("background-color: rgb(255, 242, 242);\n"
"border-radius: 7px;\n"
"color: rgb(45, 51, 107);\n"
"")
        self.booking_date_lbl.setObjectName("booking_date_lbl")
        self.gridLayout_2.addWidget(self.booking_date_lbl, 5, 1, 1, 1)
        self.emai_label = QtWidgets.QLabel(parent=Form)
        self.emai_label.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.emai_label.setFont(font)
        self.emai_label.setStyleSheet("color: rgb(255, 242, 242);\n"
"border-radius: 7px;\n"
"")
        self.emai_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.emai_label.setObjectName("emai_label")
        self.gridLayout_2.addWidget(self.emai_label, 2, 0, 1, 1)
        self.full_name_input = QtWidgets.QLineEdit(parent=Form)
        self.full_name_input.setMinimumSize(QtCore.QSize(0, 30))
        self.full_name_input.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.full_name_input.setFont(font)
        self.full_name_input.setStyleSheet("background-color: rgb(255, 242, 242);\n"
"border-radius: 7px;\n"
"color: rgb(45, 51, 107);\n"
"")
        self.full_name_input.setObjectName("full_name_input")
        self.gridLayout_2.addWidget(self.full_name_input, 1, 1, 1, 1)
        self.id_show_label = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.id_show_label.setFont(font)
        self.id_show_label.setStyleSheet("background-color: rgb(255, 242, 242);\n"
"border-radius: 7px;\n"
"color: rgb(45, 51, 107);\n"
"")
        self.id_show_label.setObjectName("id_show_label")
        self.gridLayout_2.addWidget(self.id_show_label, 0, 1, 1, 1)
        self.phone_input = QtWidgets.QLineEdit(parent=Form)
        self.phone_input.setMinimumSize(QtCore.QSize(0, 30))
        self.phone_input.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.phone_input.setFont(font)
        self.phone_input.setStyleSheet("background-color: rgb(255, 242, 242);\n"
"border-radius: 7px;\n"
"color: rgb(45, 51, 107);\n"
"")
        self.phone_input.setObjectName("phone_input")
        self.gridLayout_2.addWidget(self.phone_input, 3, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=Form)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 242, 242);\n"
"border-radius: 7px;\n"
"")
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 4, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 242, 242);\n"
"border-radius: 7px;\n"
"")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(parent=Form)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 242, 242);\n"
"border-radius: 7px;\n"
"")
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 5, 0, 1, 1)
        self.name_label = QtWidgets.QLabel(parent=Form)
        self.name_label.setMinimumSize(QtCore.QSize(0, 30))
        self.name_label.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.name_label.setFont(font)
        self.name_label.setStyleSheet("color: rgb(255, 242, 242);\n"
"border-radius: 7px;\n"
"")
        self.name_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.name_label.setObjectName("name_label")
        self.gridLayout_2.addWidget(self.name_label, 1, 0, 1, 1)
        self.clear_field_button = QtWidgets.QPushButton(parent=Form)
        self.clear_field_button.setMinimumSize(QtCore.QSize(150, 30))
        self.clear_field_button.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.clear_field_button.setFont(font)
        self.clear_field_button.setStyleSheet("QPushButton {\n"
"    background-color: rgb(45, 51, 107);\n"
"    border-radius: 7px;\n"
"    color: rgb(255, 242, 242);\n"
"    \n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(255, 242, 242);\n"
"    border-radius: 7px;\n"
"    color: rgb(120, 134, 199);\n"
"}\n"
"")
        self.clear_field_button.setObjectName("clear_field_button")
        self.gridLayout_2.addWidget(self.clear_field_button, 6, 0, 1, 1)
        self.email_input = QtWidgets.QLineEdit(parent=Form)
        self.email_input.setMinimumSize(QtCore.QSize(0, 30))
        self.email_input.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.email_input.setFont(font)
        self.email_input.setStyleSheet("background-color: rgb(255, 242, 242);\n"
"border-radius: 7px;\n"
"color: rgb(45, 51, 107);\n"
"")
        self.email_input.setObjectName("email_input")
        self.gridLayout_2.addWidget(self.email_input, 2, 1, 1, 1)
        self.booking_id_lbl = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.booking_id_lbl.setFont(font)
        self.booking_id_lbl.setStyleSheet("background-color: rgb(255, 242, 242);\n"
"border-radius: 7px;\n"
"color: rgb(45, 51, 107);\n"
"")
        self.booking_id_lbl.setObjectName("booking_id_lbl")
        self.gridLayout_2.addWidget(self.booking_id_lbl, 4, 1, 1, 1)
        self.update_button = QtWidgets.QPushButton(parent=Form)
        self.update_button.setMinimumSize(QtCore.QSize(150, 30))
        self.update_button.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.update_button.setFont(font)
        self.update_button.setStyleSheet("QPushButton {\n"
"    background-color: rgb(45, 51, 107);\n"
"    border-radius: 7px;\n"
"    color: rgb(255, 242, 242);\n"
"    \n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(255, 242, 242);\n"
"    border-radius: 7px;\n"
"    color: rgb(120, 134, 199);\n"
"}\n"
"")
        self.update_button.setObjectName("update_button")
        self.gridLayout_2.addWidget(self.update_button, 6, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 1, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.refresh_button.setText(_translate("Form", "Refresh"))
        self.delete_button.setText(_translate("Form", "Delete"))
        self.back_tomain_menu.setText(_translate("Form", "Back to main menu"))
        self.label.setText(_translate("Form", "Customer Management"))
        self.phone_label.setText(_translate("Form", "Phone Num"))
        self.booking_date_lbl.setText(_translate("Form", "booking da"))
        self.emai_label.setText(_translate("Form", "Email"))
        self.id_show_label.setText(_translate("Form", "cus id here"))
        self.label_3.setText(_translate("Form", "Booking ID"))
        self.label_2.setText(_translate("Form", "ID"))
        self.label_4.setText(_translate("Form", "Booking date"))
        self.name_label.setText(_translate("Form", "Full Name"))
        self.clear_field_button.setText(_translate("Form", "Clear fields"))
        self.booking_id_lbl.setText(_translate("Form", "booking id"))
        self.update_button.setText(_translate("Form", "Update_customer"))
