# Form implementation generated from reading ui file 'main_page.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
import os
from PyQt6.QtGui import QPixmap


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        basedir = os.path.dirname(os.path.abspath(__file__))
        Form.setObjectName("Form")
        Form.resize(733, 580)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Ignored, QtWidgets.QSizePolicy.Policy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(0, 0))
        palette = Form.palette()
        palette.setColor(QtGui.QPalette.ColorRole.Window, QtGui.QColor(169, 181, 223))
        Form.setAutoFillBackground(True)
        Form.setPalette(palette)

        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(-1, 50, -1, 50)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Ignored, QtWidgets.QSizePolicy.Policy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(675, 0))
        self.label.setMaximumSize(QtCore.QSize(900, 105))
        font = QtGui.QFont()
        font.setFamily("Sitka Heading")
        font.setPointSize(36)
        font.setBold(False)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label.setStyleSheet("color: rgb(45, 51, 107);\n"
"background-color: rgb(255, 242, 242);\n"
"border-radius: 10px;\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetNoConstraint)
        self.gridLayout.setContentsMargins(50, 25, 51, 50)
        self.gridLayout.setSpacing(50)
        self.gridLayout.setObjectName("gridLayout")
        self.manage_rooms_btn = QtWidgets.QPushButton(parent=Form)
        self.manage_rooms_btn.setMinimumSize(QtCore.QSize(161, 61))
        self.manage_rooms_btn.setStyleSheet("QPushButton{\n"
"    font-size: 25px;\n"
"    background-color: rgb(45, 51, 107);\n"
"    color: rgb(255, 242, 242);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: #FFF2F2;\n"
"    color: #2D336B;\n"
"    border: 1 px solid #aaa;\n"
"}")
        self.manage_rooms_btn.setObjectName("manage_rooms_btn")
        self.gridLayout.addWidget(self.manage_rooms_btn, 0, 1, 1, 1)
        self.manage_bookings_btn = QtWidgets.QPushButton(parent=Form)
        self.manage_bookings_btn.setMinimumSize(QtCore.QSize(161, 61))
        self.manage_bookings_btn.setStyleSheet("QPushButton{\n"
"    font-size: 19px;\n"
"    background-color: rgb(45, 51, 107);\n"
"    color: rgb(255, 242, 242);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: #FFF2F2;\n"
"    color: #2D336B;\n"
"    border: 1 px solid #aaa;\n"
"}")
        self.manage_bookings_btn.setObjectName("manage_bookings_btn")
        self.gridLayout.addWidget(self.manage_bookings_btn, 0, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Ignored, QtWidgets.QSizePolicy.Policy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setText("")
        icon_path1 = os.path.join(basedir, "icon/rooms.jpg")
        self.label_3.setPixmap(QtGui.QPixmap(icon_path1))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Ignored, QtWidgets.QSizePolicy.Policy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setText("")
        
        icon_path = os.path.join(basedir, "icon/users4.png")
        self.label_2.setPixmap(QtGui.QPixmap(icon_path))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Ignored, QtWidgets.QSizePolicy.Policy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setText("")
        icon_path3 = os.path.join(basedir, "icon/booking-bookings.jpg")
        self.label_4.setPixmap(QtGui.QPixmap(icon_path3))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 2, 1, 1)
        self.manage_customers_btn = QtWidgets.QPushButton(parent=Form)
        self.manage_customers_btn.setMinimumSize(QtCore.QSize(161, 61))
        self.manage_customers_btn.setStyleSheet("QPushButton{\n"
"    font-size: 19px;\n"
"    background-color: rgb(45, 51, 107);\n"
"    color: rgb(255, 242, 242);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: #FFF2F2;\n"
"    color: #2D336B;\n"
"    border: 1 px solid #aaa;\n"
"}")
        self.manage_customers_btn.setObjectName("manage_customers_btn")
        self.gridLayout.addWidget(self.manage_customers_btn, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Hotel Booking Admin System"))
        self.manage_rooms_btn.setText(_translate("Form", "View Rooms"))
        self.manage_bookings_btn.setText(_translate("Form", "Manage Bookings"))
        self.manage_customers_btn.setText(_translate("Form", "Manage Customers"))
