# Form implementation generated from reading ui file 'room_management_page.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(907, 642)
        Form.setMinimumSize(QtCore.QSize(907, 642))
        palette = Form.palette()
        palette.setColor(QtGui.QPalette.ColorRole.Window, QtGui.QColor(169, 181, 223))
        Form.setAutoFillBackground(True)
        Form.setPalette(palette)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setSpacing(25)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label1 = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(45)
        self.label1.setFont(font)
        self.label1.setStyleSheet("background-color: rgb(255, 242, 242);\n"
"border-radius: 7px;\n"
"color: rgb(45, 51, 107);\n"
"")
        self.label1.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label1.setObjectName("label1")
        self.verticalLayout.addWidget(self.label1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(15, 15, 20, 20)
        self.gridLayout.setSpacing(25)
        self.gridLayout.setObjectName("gridLayout")
        self.calendarWidget = QtWidgets.QCalendarWidget(parent=Form)
        self.calendarWidget.setStyleSheet("background-color: rgb(45, 51, 107);\n"
"alternate-background-color: rgb(120, 134, 199);\n"
"color: rgb(255, 242, 242);\n"
"\n"
"QCalendarWidget {\n"
"    \n"
"    border-radius: 15px;\n"
"   \n"
"}\n"
"QCalendarWidget QMenu {\n"
"    border-radius: 10px;\n"
"   \n"
"}\n"
"")
        self.calendarWidget.setObjectName("calendarWidget")
        self.gridLayout.addWidget(self.calendarWidget, 0, 0, 2, 1)
        self.label = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(45, 51, 107);")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.selected_date_label = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.selected_date_label.setFont(font)
        self.selected_date_label.setStyleSheet("color: rgb(45, 51, 107);")
        self.selected_date_label.setObjectName("selected_date_label")
        self.gridLayout.addWidget(self.selected_date_label, 1, 1, 1, 1)
        self.rooms_view = QtWidgets.QTableView(parent=Form)
        self.rooms_view.setStyleSheet("background-color: rgb(255, 242, 242);\n"
"color: rgb(45, 51, 107);\n"
"border-radius: 10px;")
        self.rooms_view.setObjectName("rooms_view")
        self.gridLayout.addWidget(self.rooms_view, 2, 0, 1, 3)
        self.view_rooms_btn = QtWidgets.QPushButton(parent=Form)
        self.view_rooms_btn.setMinimumSize(QtCore.QSize(0, 25))
        self.view_rooms_btn.setMaximumSize(QtCore.QSize(500, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        self.view_rooms_btn.setFont(font)
        self.view_rooms_btn.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 242, 242);\n"
"    border-radius: 7px;\n"
"    color: rgb(45, 51, 107);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(45, 51, 107);\n"
"    color: rgb(255, 242, 242);\n"
"}")
        self.view_rooms_btn.setObjectName("view_rooms_btn")
        self.gridLayout.addWidget(self.view_rooms_btn, 3, 0, 1, 1)
        self.back_to_main = QtWidgets.QPushButton(parent=Form)
        self.back_to_main.setMinimumSize(QtCore.QSize(150, 25))
        self.back_to_main.setMaximumSize(QtCore.QSize(350, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.back_to_main.setFont(font)
        self.back_to_main.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 242, 242);\n"
"    border-radius: 7px;\n"
"    color: rgb(45, 51, 107);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(45, 51, 107);\n"
"    color: rgb(255, 242, 242);\n"
"}")
        self.back_to_main.setObjectName("back_to_main")
        self.gridLayout.addWidget(self.back_to_main, 3, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label1.setText(_translate("Form", "Rooms "))
        self.label.setText(_translate("Form", "Selected date: "))
        self.selected_date_label.setText(_translate("Form", "date"))
        self.view_rooms_btn.setText(_translate("Form", "Show rooms for chosen date "))
        self.back_to_main.setText(_translate("Form", "Back to main menu"))
